server:
  port: 8085

spring:
  profiles:
    active: dev
  jpa:
    database: POSTGRESQL
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

security:
  secret: thisismysupersecretsigningkey
  expiration: 86400000
